MVC_Project_FoodOrder/Controllers/FoodItemsController.cs
using MVC_Project_FoodOrder.Models;
using MVC_Project_FoodOrder.ViewModels;
using System.Data.Entity;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using X.PagedList;
using System.Threading;

namespace MVC_Project_FoodOrder.Controllers
{
    [Authorize(Roles = "Admin, Consumers")]
    public class FoodItemsController : Controller
    {
        private readonly FoodDbContext db = new FoodDbContext();
        // GET: FoodItems
        public ActionResult Index()
        {
           
            return View();
        }
        public PartialViewResult FoodItemTable(int pg = 1)
        {
            //var data = db.FoodItems.OrderBy(x => x.FoodItemId).ToPagedList(pg, 5);//lazy loading
            var data = db.FoodItems
                .Include(x => x.Orders)
                .Include(x => x.Category)               
                .OrderBy(x => x.FoodItemId)
                .ToPagedList(pg, 2);
            Thread.Sleep(1000); 
            return PartialView("_FoodItemTable", data);
        }
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
           
            return View();
        }
        public ActionResult CreateForm()
        {
            FoodInputModel model = new FoodInputModel();
            model.Orders.Add(new Order());
            ViewBag.Categories = db.Categories.ToList();
            return PartialView("_CreateForm", model);
        }
        [HttpPost]
        public ActionResult Create(FoodInputModel model, string act = "")
        {
            if (act == "add")
            {
                model.Orders.Add(new Order());
                foreach (var e in ModelState.Values)
                {
                    e.Errors.Clear();
                    e.Value = null;
                }
            }
            if (act.StartsWith("remove"))
            {
                int index = int.Parse(act.Substring(act.IndexOf("_") + 1));
                model.Orders.RemoveAt(index);
                foreach (var e in ModelState.Values)
                {
                    e.Errors.Clear();
                    e.Value = null;
                }
            }
            if (act == "insert")
            {
                if (ModelState.IsValid)
                {
                    var fooditem = new FoodItem
                    {
                        CategoryId = model.CategoryId,
                        FoodName = model.FoodName,
                        UnitPrice = model.UnitPrice,                        
                        Available = model.Available
                    };
                    string ext = Path.GetExtension(model.Picture.FileName);
                    string f = Path.GetFileNameWithoutExtension(Path.GetRandomFileName()) + ext;
                    string savePath = Path.Combine(Server.MapPath("~/Pictures"), f);
                    model.Picture.SaveAs(savePath);
                    fooditem.Picture = f;

                    db.FoodItems.Add(fooditem);
                    db.SaveChanges();
                    foreach (var s in model.Orders)
                    {
                        db.Database.ExecuteSqlCommand($@"EXEC InsertOrder '{s.OrderDate}', {s.Quantity}, {(int)s.OrderType},  {fooditem.FoodItemId}");
                    }
                    FoodInputModel newmodel = new FoodInputModel() { FoodName = "" };
                    newmodel.Orders.Add(new Order());
                    ViewBag.Categories = db.Categories.ToList();
                    foreach (var e in ModelState.Values)
                    {

                        e.Value = null;
                    }
                    return View("_CreateForm", newmodel);
                }
            }
            ViewBag.Categories = db.Categories.ToList();
            return View("_CreateForm", model);
        }
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id)
        {

            ViewBag.Id = id;
            return View();
        }
        public ActionResult EditForm(int id)
        {
            var data = db.FoodItems.FirstOrDefault(x => x.FoodItemId == id);
            if (data == null) return new HttpNotFoundResult();
            db.Entry(data).Collection(x => x.Orders).Load();
            FoodEditModel model = new FoodEditModel
            {
                FoodItemId = id,
                CategoryId = data.CategoryId,               
                FoodName = data.FoodName,
                UnitPrice = data.UnitPrice,
                Available = data.Available,
                Orders = data.Orders.ToList()
            };
            ViewBag.Categories = db.Categories.ToList();          
            ViewBag.CurrentPic = data.Picture;
            return PartialView("_EditForm", model);
        }

        [HttpPost]
        public ActionResult Edit(FoodEditModel model, string act = "")
        {
            if (act == "add")
            {
                model.Orders.Add(new Order());
                foreach (var e in ModelState.Values)
                {
                    e.Errors.Clear();
                    e.Value = null;
                }
            }
            if (act.StartsWith("remove"))
            {
                int index = int.Parse(act.Substring(act.IndexOf("_") + 1));
                model.Orders.RemoveAt(index);
                foreach (var e in ModelState.Values)
                {
                    e.Errors.Clear();
                    e.Value = null;
                }
            }
            if (act == "update")
            {
                if (ModelState.IsValid)
                {
                    var food = db.FoodItems.FirstOrDefault(x => x.FoodItemId == model.FoodItemId);
                    if (food == null) { return new HttpNotFoundResult(); }
                    food.FoodName = model.FoodName;
                    food.UnitPrice = model.UnitPrice;
                    food.Available = model.Available;
                    food.CategoryId = model.CategoryId;
                    if (model.Picture != null)
                    {
                        string ext = Path.GetExtension(model.Picture.FileName);
                        string f = Path.GetFileNameWithoutExtension(Path.GetRandomFileName()) + ext;
                        string savePath = Path.Combine(Server.MapPath("~/Pictures"), f);
                        model.Picture.SaveAs(savePath);
                        food.Picture = f;
                    }

                    db.SaveChanges();
                    db.Database.ExecuteSqlCommand($"EXEC DeleteOrderByFoodItemId {food.FoodItemId}");
                    foreach (var s in model.Orders)
                    {
                        db.Database.ExecuteSqlCommand($"EXEC InsertOrder '{s.OrderDate}', {s.Quantity}, {(int)s.OrderType}, {food.FoodItemId}");
                    }


                }
            }
            ViewBag.Categories = db.Categories.ToList();
            ViewBag.CurrentPic = db.FoodItems.FirstOrDefault(x => x.FoodItemId == model.FoodItemId)?.Picture;
            return View("_EditForm", model);
        }
        [HttpPost]
        public ActionResult Delete(int id)
        {
            var fooditem = db.FoodItems.FirstOrDefault(x => x.FoodItemId == id);
            if (fooditem == null) return new HttpNotFoundResult();
            db.Orders.RemoveRange(fooditem.Orders.ToList());
            db.FoodItems.Remove(fooditem);
            db.SaveChanges();
            return Json(new { success = true });
        }
        public ActionResult CreateOrder()
        {
            var model = new Order();
            ViewBag.FoodItems = db.FoodItems.ToList();
            return View(model);
        }
        [HttpPost]
        public ActionResult CreateOrder(Order model)
        {

            if (ModelState.IsValid)
            {
                var order = new Order
                {
                    FoodItemId = model.FoodItemId,
                    OrderDate = model.OrderDate,
                    Quantity = model.Quantity,
                    OrderType = model.OrderType                
                };
                db.Orders.Add(order);
                db.SaveChanges();

                return RedirectToAction("Index");

            }
            ViewBag.FoodItems = db.FoodItems.ToList();
            return View(model);
        }
        [HttpPost]
        public ActionResult OrderDelete(int id)
        {
            var order = db.Orders.FirstOrDefault(x => x.OrderId == id);
            if (order == null) return new HttpNotFoundResult();
            db.Orders.Remove(order);
            db.SaveChanges();
            return Json(new { success = true });
        }
    }
}

MVC_Project_FoodOrder/Views/FoodItems/Create.cshtml
@model MVC_Project_FoodOrder.ViewModels.FoodInputModel
@{
    ViewBag.Title = "Create";
}

<div class="row">
    <div class="col-12">
        <div id="form-div">
            @Html.Action("CreateForm");
        </div>
    </div>
</div>

@section scripts {
    <script src="~/Scripts/jquery-3.7.1.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
}

MVC_Project_FoodOrder/Views/FoodItems/CreateOrder.cshtml
@model MVC_Project_FoodOrder.Models.Order
@{
    ViewBag.Title = "CreateOrder";
}


<h2>CreateOrder</h2>
<div class="row">
    <div class="col-12">
        @using (Html.BeginForm("CreateOrder", "FoodItems", FormMethod.Post))
        {

            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.FoodItemId, new { @class = "col-from-label col-2 text-end" })
                <div class="col-4">
                    @Html.DropDownListFor(x => x.FoodItemId, new SelectList(ViewBag.FoodItems, "FoodItemId", "FoodName"), "Select order", new { @class = "form-select" })
                    @Html.ValidationMessageFor(x => x.FoodItemId, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.OrderDate, new { @class = "col-form-lable col-2 text-end" })
                <div class="col-4">
                    @Html.TextBoxFor(x => x.OrderDate, new { @class = "form-control",type="date" })
                    @Html.ValidationMessageFor(x => x.OrderDate, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.Quantity, new { @class = "col-form-lable col-2 text-end" })
                <div class="col-4">
                    @Html.TextBoxFor(x => x.Quantity, new { @class = "form-control" ,type="number"})
                    @Html.ValidationMessageFor(x => x.Quantity, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.OrderType, new { @class = "col-form-lable col-2 text-end" })
                <div class="col-4">
                    @Html.EnumDropDownListFor(x => x.OrderType, new { @class = "form-select" })
                    @Html.ValidationMessageFor(x => x.OrderType, "", new { @class = "text-danger" })
                </div>
            </div>


            <button type="submit" name="act" value="add" class="btn btn-info">Save</button>
        }
    </div>
</div>

MVC_Project_FoodOrder/Views/FoodItems/Edit.cshtml
@model MVC_Project_FoodOrder.ViewModels.FoodEditModel

@{
    ViewBag.Title = "Edit";
}


<div class="row">
    <div class="col-12">

        <div id="form-div">
            @Html.Action("EditForm", new { id = ViewBag.Id })

        </div>
    </div>
</div>
@section scripts
{
    <script src="~/Scripts/jquery-3.7.1.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script>
        function onSuccess() {

        }
    </script>

}

MVC_Project_FoodOrder/Views/FoodItems/Index.cshtml
@model IEnumerable<MVC_Project_FoodOrder.Models.FoodItem>
@{
    ViewBag.Title = "Index";
}
<div class="row">
    <div class="col-12">

        <h2 style="text-align:center">Food Items</h2>
        <div class="d-flex justify-content-end mb-1">
            @*@Html.ActionLink("Create New", "Create", "FoodItems", new { }, new { @class = "btn btn-primary btn-sm" })*@
            <a class="btn btn-outline-success" href="@Url.Action("Create", "FoodItems")"><i class="bi bi-plus-circle-fill"></i></a>
        </div>
        <div class="spinner-border text-danger" role="status" id="spinner" style="display:none">
            <span class="visually-hidden">Loading...</span>
        </div>
        <div id="table-div">
            @Html.Action("FoodItemTable")
        </div>
    </div>
</div>
@section styles
{
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
}
@section scripts
{
    <script src="~/Scripts/jquery-3.7.1.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script>
        $(document).on("click", "button.show", function () {
            var showBtn = $(this);
            var hideBtn = showBtn.next();
            var trSh = showBtn.closest("tr");
            var trSt = trSh.next();
            showBtn.hide();
            hideBtn.show();
            trSt.show();
        });
        $(document).on("click", "button.hide", function () {
            var hideBtn = $(this);
            var showBtn = hideBtn.prev();
            var trSh = showBtn.closest("tr");
            var trSt = trSh.next();
            showBtn.show();
            hideBtn.hide();
            trSt.hide();
        });
    </script>
    <script>
        $(document).on("click", "button.del", function () {
            var id = $(this).data("pk");
            var trP = $(this).closest('tr');
            var trS = trP.next();
            if (confirm("Are you sure to delete?\nFoodItem with orders will be deleted.")) {
                $.ajax({
                    url: "/FoodItems/Delete/" + id,
                    method: "post",
                    dataType: "json",
                    success: r => {
                        if (r.success == true) {
                            trP.remove();
                            trS.remove();
                        }
                    }
                })
            }
        });
        $(document).on("click", ".dels", function () {
            var id = $(this).data("pk");
            var trP = $(this).closest('tr');
            var trS = trP.next();
            if (confirm("Are you sure to delete?")) {
                $.ajax({
                    url: "/FoodItems/OrderDelete/" + id,
                    method: "post",
                    dataType: "json",
                    success: r => {
                        if (r.success == true) {
                            trP.remove();
                            trS.remove();
                        }
                    }
                })
            }
        });

    </script>
}

MVC_Project_FoodOrder/Views/FoodItems/_CreateForm.cshtml
@model MVC_Project_FoodOrder.ViewModels.FoodInputModel
@using (Ajax.BeginForm("Create",
"FoodItems", new { },
new AjaxOptions
{
    HttpMethod = "POST",
    InsertionMode = InsertionMode.Replace,
    UpdateTargetId = "form-div",
    OnSuccess = "onSuccess"
},
new { id = "frm", enctype = "multipart/form-data" }))
{
    <h2>Create new fooditem</h2>
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.CategoryId, new { @class = "col-form-label col-2 text-end" })
        <div class="col-4">
            @Html.DropDownListFor(x => x.CategoryId, new SelectList(ViewBag.Categories, "CategoryId", "CategoryName"), "Select category", new { @class = "form-select" })
            @Html.ValidationMessageFor(x => x.CategoryId, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.FoodName, new { @class = "col-form-label col-2 text-end" })
        <div class="col-4">
            @Html.TextBoxFor(x => x.FoodName, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.FoodName, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.UnitPrice, new { @class = "col-form-label col-2 text-end" })
        <div class="col-4">
            @Html.TextBoxFor(x => x.UnitPrice, new { @class = "form-control", type = "number" })
            @Html.ValidationMessageFor(x => x.UnitPrice, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.Picture, new { @class = "col-form-label col-2 text-end" })
        <div class="col-4">
            @Html.TextBoxFor(x => x.Picture, new { @class = "form-control", type = "file" })
            @Html.ValidationMessageFor(x => x.Picture, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row mb-1">
        <div class="col-4 offset-2">
            <div class="form-check">
                @Html.CheckBoxFor(x => x.Available)
                <label class="form-check-label">
                    Available ?
                </label>
            </div>
        </div>

    </div>
    <div class="col-6">
        <div class="d-flex justify-content-between">
            <h4>Orders</h4>
            <button type="submit" name="act" value="add" class="btn btn-secondary btn-sm" formnovalidate>+</button>
        </div>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Order Date</th>
                    <th>Quantity</th>
                    <th>Order Type</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @for (var i = 0; i < Model.Orders.Count; i++)
                {
                    <tr>
                        <td>
                            @Html.TextBoxFor(x => Model.Orders[i].OrderDate, new { @class = "form-control", type = "date" })
                            @Html.ValidationMessageFor(x => Model.Orders[i].OrderDate, "", new { @class = "text-danger" })
                        </td>
                        <td>
                            @Html.TextBoxFor(x => Model.Orders[i].Quantity, new { @class = "form-control", type = "number" })
                            @Html.ValidationMessageFor(x => Model.Orders[i].Quantity, "", new { @class = "text-danger" })
                        </td>
                        <td>
                            @Html.EnumDropDownListFor(x => Model.Orders[i].OrderType, new { @class = "form-select" })
                            @Html.ValidationMessageFor(x => Model.Orders[i].OrderType, "", new { @class = "text-danger" })
                        </td>
                        <td>
                            <button type="submit" name="act" value="remove_@i" class="btn btn-danger btn-sm" formnovalidate>Remove</button>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="col-4 offset-2">
        <button type="submit" name="act" value="insert" class="btn btn-primary">Save</button>
    </div>
    <div class="">
        @Html.ActionLink("Go to Previous page", "Index", "FoodItems", new { }, new { @class = "nav-link d-flex justify-content-center" })
    </div>
}

MVC_Project_FoodOrder/Views/FoodItems/_EditForm.cshtml
@model MVC_Project_FoodOrder.ViewModels.FoodEditModel
@using (Ajax.BeginForm("Edit",
"FoodItems", new { },
new AjaxOptions
{
    HttpMethod = "POST",
    InsertionMode = InsertionMode.Replace,
    UpdateTargetId = "form-div",
    OnSuccess = "onSuccess"
},
new { id = "frm", enctype = "multipart/form-data" }))
{
    <h2>Edit fooditem</h2>
    @Html.HiddenFor(x => x.FoodItemId)
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.CategoryId, new { @class = "col-form-label col-2 text-end" })
        <div class="col-4">
            @Html.DropDownListFor(x => x.CategoryId, new SelectList(ViewBag.Categories, "CategoryId", "CategoryName"), "Select category", new { @class = "form-select" })
            @Html.ValidationMessageFor(x => x.CategoryId, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.FoodName, new { @class = "col-form-label col-2 text-end" })
        <div class="col-4">
            @Html.TextBoxFor(x => x.FoodName, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.FoodName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.UnitPrice, new { @class = "col-form-label col-2 text-end" })
        <div class="col-4">
            @Html.TextBoxFor(x => x.UnitPrice, new { @class = "form-control", type = "number" })
            @Html.ValidationMessageFor(x => x.UnitPrice, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.Picture, new { @class = "col-form-label col-2 text-end" })
        <div class="col-4">
            @Html.TextBoxFor(x => x.Picture, new { @class = "form-control", type = "file" })
            @Html.ValidationMessageFor(x => x.Picture, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row mb-1">
        <div class="col-4 offset-2">
            <div class="form-check">
                @Html.CheckBoxFor(x => x.Available)
                <label class="form-check-label">
                    Available ?
                </label>
            </div>
        </div>
    </div>
    <div class="col-6 offset-2">
        <img src="~/Pictures/@ViewBag.CurrentPic" style="width:120px;margin:20px" class="img-thumbnail" />
    </div>
    <div class="col-6">
        <div class="d-flex justify-content-between">
            <h4>Orders</h4>
            <button type="submit" name="act" value="add" class="btn btn-secondary btn-sm" formnovalidate>+</button>
        </div>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Order Date</th>
                    <th>Quantity</th>
                    <th>Order Type</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @for (var i = 0; i < Model.Orders.Count; i++)
                {
                    <tr>
                        <td>
                            @Html.TextBoxFor(x => Model.Orders[i].OrderDate, new { @class = "form-control", type = "date", @Value = DateTime.Today.ToString("yyyy-MM-dd") })
                            @Html.ValidationMessageFor(x => Model.Orders[i].OrderDate, "", new { @class = "text-danger" })
                        </td>
                        <td>
                            @Html.TextBoxFor(x => Model.Orders[i].Quantity, new { @class = "form-control", type = "number" })
                            @Html.ValidationMessageFor(x => Model.Orders[i].Quantity, "", new { @class = "text-danger" })
                        </td>
                        <td>
                            @Html.EnumDropDownListFor(x => Model.Orders[i].OrderType, new { @class = "form-select" })
                            @Html.ValidationMessageFor(x => Model.Orders[i].OrderType, "", new { @class = "text-danger" })
                        </td>
                        <td>
                            <button type="submit" name="act" value="remove_@i" class="btn btn-danger btn-sm" formnovalidate>Remove</button>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="col-4 offset-2">
        <button type="submit" name="act" value="update" class="btn btn-primary">Save</button>
    </div>
    @*<div class="">
        @Html.ActionLink("Go to Previous page", "Index", "FoodItems", new { }, new { @class = "nav-link d-flex justify-content-center" })
    </div>*@

}

MVC_Project_FoodOrder/Views/FoodItems/_FoodItemTable.cshtml
@model IEnumerable<MVC_Project_FoodOrder.Models.FoodItem>
@using X.PagedList
@using X.PagedList.Mvc
@using X.PagedList.Mvc.Common

<table class="table table-bordered">
    <thead class="table-primary">
        <tr>
            <th></th>
            <th></th>
            <th>Category</th>
            <th>Food Name</th>
            <th>Unit Price</th>
            <th>Available?</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var f in Model)
        {

            <tr style="width:40px;text-align:center">
                <td>
                    <button class="btn show"><i class="bi bi-caret-right"></i></button>
                    <button class="btn hide" style="display:none"><i class="bi bi-caret-up"></i></button>
                </td>
                <td style="width:45px;text-align:center"><img src="~/Pictures/@f.Picture" class="rounded-circle" style="width:40px" /></td>
                <td>@f.Category.CategoryName</td>
                <td>@f.FoodName</td>
                <td>@f.UnitPrice.ToString("0.00")</td>
                <td>@(f.Available ? "Yes" : "No")</td>
                <td>
                    @*@Html.ActionLink("Edit", "Edit", "FoodItems", new { id = f.FoodItemId }, new { @class = "btn btn-warning btn-sm" })*@
                    <a class="btn btn-outline-warning" href="@Url.Action("Edit", "FoodItems", new { id = f.FoodItemId})"><i class="bi bi-pen"></i></a>
                    <button data-pk="@f.FoodItemId" class="btn btn-danger del"><i class="bi bi-trash"></i></button>
                </td>
            </tr>
            <tr style="display:none">

                <td></td>
                <td colspan="6">
                    <div class="d-flex justify-content-between">
                        <h4>Orders</h4>
                        @*@Html.ActionLink("Create", "CreateOrder", "FoodItems", new { id = f.FoodItemId }, new { @class = "btn bi bi-plus-circle" })*@
                        <a class="btn btn-outline-info btn-sm" href="@Url.Action("CreateOrder", "FoodItems")"><i class="bi bi-plus-circle-fill"></i></a>
                    </div>
                    <table class="table table-bordered">
                        <thead class="table-secondary">
                            <tr>
                                <th>Order Date</th>
                                <th>Quantity</th>
                                <th>Order Type</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var o in f.Orders)
                            {
                                <tr>
                                    <td>@o.OrderDate.ToString("yyyy-MM-dd")</td>
                                    <td>@o.Quantity</td>
                                    <td>@o.OrderType</td>
                                    <td>
                                        <button data-pk="@o.OrderId" class="btn btn-outline-danger btn-sm dels"><i class="bi bi-trash"></i></button>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>

                </td>
            </tr>
        }
    </tbody>
</table>

<div class="d-flex justify-content-end">

    @Html.PagedListPager((IPagedList)Model, pg => Url.Action("FoodItemTable", "FoodItems", new { pg = pg }), PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new PagedListRenderOptions
{
    UlElementClasses = new string[] { "pagination", "pagination-sm" },
    LiElementClasses = new string[] { "page-item" },
    PageClasses = new string[] { "page-link" },
    DisplayLinkToPreviousPage = PagedListDisplayMode.Always,
    DisplayLinkToNextPage = PagedListDisplayMode.Always
},
    new AjaxOptions() { HttpMethod = "GET", UpdateTargetId = "table-div", LoadingElementId= "spinner" }))
</div>