MVC_Project_FoodOrder/Controllers/GroupingsController.cs
using MVC_Project_FoodOrder.Models;
using MVC_Project_FoodOrder.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
namespace MVC_Project_FoodOrder.Controllers
{
    public class GroupingsController : Controller
    {
        private readonly FoodDbContext db = new FoodDbContext();
        // GET: Groupings
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult GroupingByFoodName()
        {
            var data = db.Orders.Include(x => x.FoodItem).ToList()
               .GroupBy(s => s.FoodItem.FoodName)
               .Select(g => new GroupedData { Key = g.Key, Data = g.Select(x => x) })
               .ToList();
            return View(data);
        }
        public ActionResult GroupingByOrderType()
        {
            var data = db.Orders
                .ToList()
               .GroupBy(s => s.OrderType)
               .Select(g => new GroupedData { Key = g.Key.ToString(), Data = g.Select(x => x) })
               .ToList();
            return View(data);
        }
    }
}

MVC_Project_FoodOrder/Views/Shared/_Fail.cshtml
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <strong>Failed!</strong> Failed to save data.
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

MVC_Project_FoodOrder/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <script src="~/Scripts/bootstrap.bundle.js"></script>
    <style>
        body {
            padding-top: 70px;
            background-color:floralwhite;
        }

        .main {
            min-height: calc(100vh - 110px);
        }
    </style>
    @RenderSection("styles", false)
</head>
<body>


    <navbar class="navbar bg-success-subtle navbar-expand-md fixed-top shadow-sm px-2">
        <div class="container-fluid">
            <span class="navbar-brand">Food Order</span>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#nv" aria-controls="nv" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse" id="nv">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        @Html.ActionLink("Home", "Index", "Home", new { }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Categories", "Index", "Categories", new { }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("FoodItems", "Index", "FoodItems", new { }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Aggregates", "Index", "Aggregates", new { }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Grouping by Food", "GroupingByFoodName", "Groupings", new { }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Grouping by OrderType", "GroupingByOrderType", "Groupings", new { }, new { @class = "nav-link" })
                    </li>
                </ul>
                <ul class="navbar-nav ms-auto">
                    @if (Request.IsAuthenticated)
                    {
                        <li class="nav-item">
                            @Html.ActionLink("Logout", "Logout", "Account", new { }, new { @class = "nav-link" })
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            @Html.ActionLink("Register", "Register", "Account", new { }, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Login", "Login", "Account", new { }, new { @class = "nav-link" })
                        </li>
                    }
                </ul>
            </div>

        </div>
    </navbar>
    <main class="container-fluid main">
        @RenderBody()
    </main>
    <footer class="container-fluid text-center">
        <p>&copy;Welcome to My Project || 2024</p>
    </footer>
    @RenderSection("scripts", false)
</body>
</html>

MVC_Project_FoodOrder/Views/Shared/_Success.cshtml
<div class="alert alert-success alert-dismissible fade show" role="alert">
    <strong>Success!</strong> Data saved.
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>